os:
  - linux
language: csharp
mono: none
dotnet: 3.1
branches:
  only:
    - master
before_install:
  - chmod +x ./scripts/build.sh
install:
  - dotnet restore ./src/IntroToAlgorithms/
before script:
  - export PATH=$PATH:/home/travis/.dotnet/tools
script:
- ./scripts/build.sh
